---
  - name: Run Dockerized Flask Application
    docker_container:
      name: flask-app
      image: kabirgupta3/sample-flask-app
      state: started
      detach: yes
      ports:
      - "5000:5000"
